// Tingkatan musuh: easy -> super power extreme
export const LEVELS = [
  {
    id: 'easy',
    label: 'EASY',
    name: 'Rookie Rob',
    color: '#4ade80',
    hp: 60,
    dmg: 4,
    speed: 2.0,
    attackRange: 1.7,
    attackCooldown: 2.1,
    taunt: 'Pelan-pelan... dia masih pemula.',
  },
  {
    id: 'normal',
    label: 'NORMAL',
    name: 'Club Caz',
    color: '#60a5fa',
    hp: 95,
    dmg: 7,
    speed: 2.6,
    attackRange: 1.8,
    attackCooldown: 1.6,
    taunt: 'Dia mulai serius. Jaga jarak!',
  },
  {
    id: 'hard',
    label: 'HARD',
    name: 'Iron Ika',
    color: '#fb923c',
    hp: 135,
    dmg: 11,
    speed: 3.1,
    attackRange: 1.9,
    attackCooldown: 1.2,
    taunt: 'Sakit! Iron Ika memukul keras.',
  },
  {
    id: 'super',
    label: 'SUPER',
    name: 'Super Seno',
    color: '#e879f9',
    hp: 185,
    dmg: 14,
    speed: 3.7,
    attackRange: 2.0,
    attackCooldown: 0.95,
    taunt: 'Super Seno super cepat. BLOCK!',
  },
  {
    id: 'extreme',
    label: 'POWER EXTREME',
    name: 'EXTREME X',
    color: '#ef4444',
    hp: 260,
    dmg: 18,
    speed: 4.3,
    attackRange: 2.2,
    attackCooldown: 0.75,
    taunt: 'POWER EXTREME! Jangan panik, Mino!',
  },
]

export const PUNCHES = {
  jab: { dmg: 7, range: 2.0, cooldown: 0.38, knock: 2.2, label: 'JAB' },
  hook: { dmg: 11, range: 1.9, cooldown: 0.65, knock: 4.0, label: 'HOOK' },
  upper: { dmg: 16, range: 1.8, cooldown: 1.0, knock: 6.5, label: 'UPPERCUT' },
}
